### ISSUE TITLE
Intermittent Crash when traveling through Wormhole

### ISSUE THREAD

**Issue by czer323** [Slazanger/SMT#10]
When traveling through wormholes to unknown space, SMT typically crashes.  Please advise if there are any typical troubleshooting methods or logs to provide.

See Event Viewer - Application log entries :
```
Application: SMT.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Net.WebException
   at System.Net.ConnectStream.Read(Byte[], Int32, Int32)
   at System.IO.StreamReader.ReadBuffer()
   at System.IO.StreamReader.ReadToEnd()
   at SMT.EVEData.ZKillRedisQ.UpdateThreadFunc()
   at System.Threading.ThreadHelper.ThreadStart_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart()

Faulting application name: SMT.exe, version: 1.0.0.0, time stamp: 0x5af5a7d1
Faulting module name: KERNELBASE.dll, version: 10.0.16299.371, time stamp: 0xee297154
Exception code: 0xe0434352
Fault offset: 0x00103ef2
Faulting process id: 0x3dbc
Faulting application start time: 0x01d3ed8eaf095e99
Faulting application path: G:\Downloads\SMT_0.44\SMT.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 5ad48d4f-d80e-4583-a378-a41a34bf6258
Faulting package full name: 
Faulting package-relative application ID: 

Fault bucket 1933513608787521631, type 5
Event Name: CLR20r3
Response: Not available
Cab Id: 0

Problem signature:
P1: SMT.exe
P2: 1.0.0.0
P3: 5af5a7d1
P4: System
P5: 4.7.2556.0
P6: 59b83638
P7: 1064
P8: bc
P9: System.Net.WebException
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERF13F.tmp.mdmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER6.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER4.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER34.tmp.txt

These files may be available here:
C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_SMT.exe_cfd4d3414b8c8eeb32a4faa7bd67936ae53535_e0dbbd3e_066a07d4

Analysis symbol: 
Rechecking for solution: 0
Report Id: 5ad48d4f-d80e-4583-a378-a41a34bf6258
Report Status: 268435456
Hashed bucket: c05fdd04472638d64ad538620c29f05f
```

**Comment by Slazanger** [comment]
I made some changes a while back and haven't seen this since, let me know if this continues to occur.
