### ISSUE TITLE
Issue: Crashes when jumping through stargate

### ISSUE THREAD

**Issue by hibatica** [Slazanger/SMT#120]
### Program crash apon jumping through stargate
I found this application yesterday and it worked perfectly fine.
Today I opened it up and found it to be crashing every time I jump through a stargate.

I tried messing with the preferences but couldn't get it to work.
I also attempted running SMT as administrator and it didn't work.

#### Possibly useful event viewer logs
```
Application: SMT.exe
CoreCLR Version: 6.0.1623.17311
.NET Version: 6.0.16
Description: The process was terminated due to an unhandled exception.
Exception Info: System.InvalidOperationException: Failed initializing notifications
 ---> System.IO.IOException: Cannot create a stable subkey under a volatile parent key.
   at Microsoft.Win32.RegistryKey.Win32Error(Int32 errorCode, String str)
   at Microsoft.Win32.RegistryKey.CreateSubKeyInternalCore(String subkey, RegistryKeyPermissionCheck permissionCheck, RegistryOptions registryOptions)
   at Microsoft.Win32.RegistryKey.CreateSubKey(String subkey, RegistryKeyPermissionCheck permissionCheck, RegistryOptions registryOptions)
   at Microsoft.Win32.RegistryKey.CreateSubKey(String subkey)
   at Microsoft.Toolkit.Uwp.Notifications.ToastNotificationManagerCompat.Initialize()
   at Microsoft.Toolkit.Uwp.Notifications.ToastNotificationManagerCompat..cctor()
   --- End of inner exception stack trace ---
   at Microsoft.Toolkit.Uwp.Notifications.ToastNotificationManagerCompat.CreateToastNotifier()
   at Microsoft.Toolkit.Uwp.Notifications.ToastContentBuilder.Show(CustomizeToast customize)
   at Microsoft.Toolkit.Uwp.Notifications.ToastContentBuilder.Show()
   at SMT.MainWindow.<>c__DisplayClass71_1.<OnCombatEvent>b__0() in D:\Projects\SMT\SMT\MainWindow.xaml.cs:line 1063
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run()
   at XamlGeneratedNamespace.GeneratedApplication.Main()
```

```
Faulting application name: SMT.exe, version: 1.0.0.0, time stamp: 0x6387d353
Faulting module name: KERNELBASE.dll, version: 10.0.22621.1635, time stamp: 0x61869dd2
Exception code: 0xe0434352
Fault offset: 0x000000000006536c
Faulting process id: 0x0x5144
Faulting application start time: 0x0x1D98DF4ED9A5161
Faulting application path: C:\Users\micha\Documents\SMT_1.20\SMT.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 85bfa3d6-ea77-4be7-805b-5b5307e7b164
Faulting package full name: 
Faulting package-relative application ID: 
```

```
Fault bucket 1827112503805654585, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: SMT.exe
P2: 1.0.0.0
P3: 6387d353
P4: KERNELBASE.dll
P5: 10.0.22621.1635
P6: 61869dd2
P7: e0434352
P8: 000000000006536c
P9: 
P10: 

Attached files:
\\?\C:\Users\micha\Documents\SMT_1.20\Sounds\woop.mp3
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.076bc42f-4cf3-4a9a-a3c5-f330ce4ee7de.tmp.dmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.803a831b-db60-46cd-b7f7-48d92a3f7305.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.619064c8-de93-42da-846f-d0df0a03615b.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.d81d1552-f3fb-4402-9f7e-abf36709c3b3.tmp.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.dd5e214b-734c-4a2b-b269-e25871d89dc6.tmp.xml

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_SMT.exe_fc2a9ccb147f8f888221240f0d4486a5ed2234c_510a9180_78233dde-4cdd-4654-8338-6c800a3be925

Analysis symbol: 
Rechecking for solution: 0
Report Id: 85bfa3d6-ea77-4be7-805b-5b5307e7b164
Report Status: 268435456
Hashed bucket: 8ff6e9f8e0a2482de95b35244a02b639
Cab Guid: 0
```

**Comment by Slazanger** [comment]
this looks like this issue : https://github.com/CommunityToolkit/WindowsCommunityToolkit/issues/4858  I'll ensure its correctly guarded though. In the short term if you disable the combat notifications it should function

**Comment by emilyd19941** [comment]
same crash. same fix seems to work! thanks slazanger!
