### ISSUE TITLE
.NET Exception when finding jump bridges

### ISSUE THREAD

**Issue by snoblitz** [Slazanger/SMT#32]
**Steps to Reproduce:**
1) Using fresh install of 078, I added ESI for 3 characters
2) Select the "Follow?" tick box for one of the 3
3) Initiate a Find Jump Bridges action
4) Wait for app to crash to desktop with no error message or prompt

This reproduced 100% of the time until I added the step of closing out of the application and restarting it between step #1 and #2 above. Once I did that, it stopped reproducing.

**.NET Exception Dump from Event Viewer**
Application: SMT.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ArgumentException
   at System.ThrowHelper.ThrowArgumentException(System.ExceptionResource)
   at System.Collections.Generic.Dictionary`2[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Insert(System.__Canon, System.__Canon, Boolean)
   at System.Net.Http.Headers.HttpHeaders.AddHeaderToStore(System.String, HeaderStoreItemInfo)
   at System.Net.Http.Headers.HttpHeaders.CreateAndAddHeaderToStore(System.String)
   at System.Net.Http.Headers.HttpHeaders.GetOrCreateHeaderInfo(System.String, Boolean)
   at System.Net.Http.Headers.HttpHeaders.SetParsedValue(System.String, System.Object)
   at System.Net.Http.Headers.HttpRequestHeaders.set_Authorization(System.Net.Http.Headers.AuthenticationHeaderValue)
   at ESI.NET.EsiRequest+<Execute>d__4`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at ESI.NET.Logic.UniverseLogic+<Structure>d__28.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at SMT.EVEData.LocalCharacter+<FindJumpGates>d__94.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at SMT.MainWindow+<ImportJumpGatesBtn_Click>d__43.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Application.RunDispatcher(System.Object)
   at System.Windows.Application.RunInternal(System.Windows.Window)
   at SMT.App.Main()

**Windows Application Error Dump**
Faulting application name: SMT.exe, version: 1.0.0.0, time stamp: 0x5e944d9d
Faulting module name: KERNELBASE.dll, version: 10.0.18362.719, time stamp: 0xb31987d3
Exception code: 0xe0434352
Fault offset: 0x000000000003a859
Faulting process id: 0x50e0
Faulting application start time: 0x01d6127d92efabd3
Faulting application path: C:\Users\snobl\Desktop\Intel\SMT.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 7f36b35b-5018-477a-ab3f-8943e1fd8078
Faulting package full name: 
Faulting package-relative application ID:

**Comment by Slazanger** [comment]
Fixed in 5620ca8
