### ISSUE TITLE
Error when building and running -- System.IO.FileNotFoundException: MapLayout.dat

### ISSUE THREAD

**Issue by Legacy** [Slazanger/SMT#4]
Tried to build this myself, but there doesn't seem to be any information on this MapLayout.dat that is missing from the folder.
```
System.IO.FileNotFoundException occurred
  HResult=0x80070002
  Message=Could not find file 'C:\Users\ricky\Documents\Visual Studio 2017\Projects\SMT-master\bin\Debug\MapLayout.dat'.
  Source=mscorlib
  StackTrace:
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy)
   at System.IO.FileStream..ctor(String path, FileMode mode)
   at SMT.EVEData.EveManager.DeserializeFromDisk[T](String Filename) in C:\Users\ricky\Documents\Visual Studio 2017\Projects\SMT-master\EVEData\EveManager.cs:line 847
   at SMT.EVEData.EveManager.LoadFromDisk() in C:\Users\ricky\Documents\Visual Studio 2017\Projects\SMT-master\EVEData\EveManager.cs:line 817
   at SMT.MainWindow..ctor() in C:\Users\ricky\Documents\Visual Studio 2017\Projects\SMT-master\MainWindow.xaml.cs:line 116

```

**Comment by Legacy** [comment]
Alright I found how to create the  data from scratch, but I can't seem to get the app to run after that

**Comment by Slazanger** [comment]
If you run with init from scratch toggled it will pull the dotlan data and cache the alliance info in one huge dump, it also requires the static data export for some of the other bits..

**Comment by Slazanger** [comment]
toggle  the following to on 
bool initFromScratch = false;

The static data export bits i use are the mapSolarSystems.csv file (I grabbed it from here ) https://www.fuzzwork.co.uk/dump/latest/mapSolarSystems.csv.bz2

**Comment by Slazanger** [comment]
I forgot to add.. once you've generated the data you can toggle that initfromscratch and you wont get mega long startups while it crunches a bunch of the data or you might want to just disable the alliance id to name cache

**Comment by Legacy** [comment]
Yeah I go past the toggle but that file not being in there threw errors, thanks for the link

**Comment by Slazanger** [comment]
you should be able to grab the matching release's data from here on github

**Comment by Slazanger** [comment]
https://github.com/Slazanger/SMT/releases/tag/SMT_030

**Comment by Legacy** [comment]
Perfect thanks :)
